apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: holamundo-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/tu_usuario/tu_repositorio.git'
    targetRevision: HEAD
    path: path/al/directorio/con/los/manifiestos
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
